FC-DEV-FinalProject/FinalProject_2VEN_BE

- src/main/java/com/sysmatic2/finalbe/member/entity/LoginLog.java
- src/main/java/com/sysmatic2/finalbe/member/entity/Member.java
<br />
Member/LoginLog 엔티티 추가
<br />
1. Member/LoginLog 엔티티 추가
> Member/LoginLog 엔티티  최초 추가

- pom.xml
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesRestController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/InvestmentAssetClassesDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/InvestmentAssetClassesPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/InvestmentAssetClassesRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/test/java/com/sysmatic2/finalbe/DbConnectionTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/InvestAssetClassesRepositoryTest.java
<br />
- 투자자산 분류 엔티티 구현
- 투자자산 분류 CRUD 구현
- Global Exception Handler 구현 
<br />
- 투자자산 분류 엔티티 구현
- 투자자산 분류 CRUD 구현
- Global Exception Handler 구현 
<br />
ex)
- Swagger(SpringDoc)
<br />
> [ADD] 투자자산 분류 구현

- src/main/java/com/sysmatic2/finalbe/config/AuditorAwareImpl.java
<br />
ex) 
bucket post 및 bucket list view 초기 구현
<br />
ex) 
1. bucket post 기본 기능 구현
2. bucket list view 기본 기능 구현
<br />
ex)
- corsheaders
- jwt
<br />
백프 배포 nginx 검토
> modify config

- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesRestController.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/InvestmentAssetClassesRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/util/InvestmentAssetClassesMapper.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/TradingTypeEntityRepositoryTest.java
- [] 기능 추가
<br />
- 페이지네이션 수정
<br />
1. 페이지네이션 첫페이지, 마지막 페이지 구현
2.페이지네이션 로직 변경 
<br />
<br />
> [Fix] IAC Pagination

- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesRestController.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/TradingTypeService.java
- src/main/java/com/sysmatic2/finalbe/util/CreatePageResponse.java
- src/main/java/com/sysmatic2/finalbe/util/InvestmentAssetClassesMapper.java
- src/main/java/com/sysmatic2/finalbe/util/TradingTypeMapper.java
- [] 기능 추가
<br />
- Page 객체 반환을 Map 반환으로 변경
- toDto, toEntity static화
<br />
- Page 객체를 반환할때 직렬화 문제 발생 -> Map 반환으로 변경
- toDto, toEntity static 메서드로 변경
<br />
<br />
> [Modify] IAC, TradingType Controller return type change

- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyStandardCodeRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StandardCodeRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/TradingTypeEntityRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
<br />
Strategy 생성 관련 엔티티 수정 및 구현
<br />
1. Strategy Entity 수정
2. Strategy Repository 추가
3. StrategyStandardCode Repository 추가
4. StrategyService 추가
5. IACRepositoryTest 변경
6. StandardCodeRepositoryTest추가
7. TradingTypeEntityRepositoryTest 추가
8. StrategyServiceTest추가
<br />
<br />
> [Add] Strategy Create 관련

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceMockTest.java
<br />
전략등록 폼
<br />
전략등록 폼에 필요한 데이터 반환하는 컨트롤러
전략 서비스 목 테스트
<br />
<br />
> feature: add registrationFormToController

- src/main/java/com/sysmatic2/finalbe/config/WebConfig.java
<br />
CORS 설정 추가
<br />
CORS 설정추가
모든 출처 허용으로 설정
<br />
<br />
> [Add] CORS configuration

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/TradingTypeController.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- [] 기능 추가
<br />
api 형태 수정
상태코드 수정
<br />
TradingTypeController - api 형태 수정, 수정/삭제 상태코드 변경
<br />
<br />
> fix TradingTypeController

- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesRestController.java
- [] 기능 추가
<br />
IAC 목록 페이지네이션 page default값 수정
<br />
IAC 목록 페이지네이션 page default값 0으로 수정
<br />
<br />
> [Fix] IAC Controller List Pagination default

- src/main/java/com/sysmatic2/finalbe/config/AuditorAwareImpl.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- [] 기능 추가
<br />
IAC 테스트 주석처리
<br />
<br />
<br />
> [Fix] iacTest Disabled

- pom.xml
- src/main/java/com/sysmatic2/finalbe/cs/controller/FAQController.java
- src/main/java/com/sysmatic2/finalbe/cs/service/FAQService.java
- src/test/java/com/sysmatic2/finalbe/cs/controller/FAQControllerTest.java
- src/test/java/com/sysmatic2/finalbe/cs/repository/FAQCategoryRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/cs/repository/FAQRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/cs/service/FAQServiceTest.java
<br />
FAQ 및 테스트 코드 수정
<br />
1. FAQ 서비스, 컨트롤러 수정
2. FAQ 테스트 코드 수정
<br />
<br />
> feat(FAQ) : modify FAQ , Test 

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- [] 기능 추가
<br />
Global Exception Handler 수정
Spring에서 사용하지 않는 예외에 대한 handler 수정
<br />
<br />
> [MODIFY] Global Exception Handler

- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesController.java
- [] 기능 추가
<br />
IAC 컨트롤러 리팩토링
<br />
1. IAC 컨트롤러명 변경
2. IAC 컨트롤러 미사용 import 제거
<br />
<br />
> [MODIFY] iacController name

- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesRestController.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/TradingTypeController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/InvestmentAssetClassesDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/InvestmentAssetClassesPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/InvestmentAssetClassesRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/TradingTypeAdminRequestDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/TradingTypeAdminResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/TradingTypeRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyIACEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/TradingTypeEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/InvestmentAssetClassesRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/TradingTypeRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/TradingTypeService.java
- src/main/java/com/sysmatic2/finalbe/util/DtoEntityConversionUtils.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/TradingTypeControllerTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyIACRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/TradingTypeRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceMockTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/TradingTypeServiceTest.java
Reverts FC-DEV-FinalProject/FinalProject_2VEN_BE#38
> Revert "Kdh/strategy detail"

- src/main/java/com/sysmatic2/finalbe/admin/controller/InvestmentAssetClassesController.java
- src/main/java/com/sysmatic2/finalbe/admin/controller/TradingTypeController.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/InvestmentAssetClassesDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/InvestmentAssetClassesPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/InvestmentAssetClassesRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/TradingTypeAdminRequestDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/TradingTypeAdminResponseDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/TradingTypeRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingTypeEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/repository/InvestmentAssetClassesRepository.java
- src/main/java/com/sysmatic2/finalbe/admin/repository/TradingTypeRepository.java
- src/main/java/com/sysmatic2/finalbe/admin/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/admin/service/TradingTypeService.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/InvestmentAssetClassesController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyRegistrationDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyIACEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/util/DtoEntityConversionUtils.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/TradingTypeControllerTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/InvestAssetClassesRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyIACRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/TradingTypeRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceMockTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/TradingTypeServiceTest.java
- [] 기능 추가
<br />
<br />
<br />
<br />
> [REFACTOR] 매매유형, 투자자산분류 admin 디렉토리로 이동

- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyIACResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyIACEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/util/DtoEntityConversionUtils.java
<br />
전략 등록시 전략 - 투자자산 분류 관계 테이블 데이터 입력 로직 추가
<br />
전략 등록시 전략 - 투자자산 분류 관계 테이블 데이터 입력 로직 추가
<br />
<br />
> [Add] 전략 등록시 전략 - 투자자산 분류 관계 테이블 데이터 입력 로직 추가

- src/main/java/com/sysmatic2/finalbe/admin/controller/InvestmentAssetClassesController.java
- src/main/java/com/sysmatic2/finalbe/admin/controller/TradingCycleController.java
- src/main/java/com/sysmatic2/finalbe/admin/controller/TradingTypeController.java
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/util/ResponseUtils.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
- [] 컨벤션 수정
<br />
exceptionhandler 정리
컨트롤러 유효성 검사 추가
<br />
ResponseUtils에 예외 폼 정의
전략 컨트롤러 단 매개변수 유효성 검사 추가
<br />
<br />
> refactor exceptionhandler 

- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingCycleEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyIACResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyIACRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
<br />
전략 상세 api 구현
<br />
1. StrategyService
2. StrategyController
3. StrategyIACRepository
4. StrategyIACResponseDto
<br />
<br />
> [Add] Strategy Detail 

- src/main/java/com/sysmatic2/finalbe/admin/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingCycleEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyIACEntity.java
<br />
ex) 
bucket post 및 bucket list view 초기 구현
<br />
ex) 
1. bucket post 기본 기능 구현
2. bucket list view 기본 기능 구현
<br />
ex)
- corsheaders
- jwt
<br />
백프 배포 nginx 검토
> [Modify] ToString exclude

- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingCycleEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
> [Modify] strategy bi directional mapping

- src/main/java/com/sysmatic2/finalbe/admin/controller/TradingCycleController.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/StrategyApprovalHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingCycleEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/TradingTypeEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyListDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyProposalEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustom.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/StrategyControllerTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/StrategyControllerWebMvcTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceMockTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceTest.java
<br />
전략 목록 구현
<br />
전략 목록 컨트롤러 구현,
테스트 코드작성
<br />
<br />
> feature: add /api/strategies

- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/StrategyControllerTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyServiceMockTest.java
- [] 기능 추가
<br />
전략 리스트  버그 수정
<br />
전략 리스트 투자자산분류 개수 만큼 중복 출력되는 버그 수정
<br />
<br />
> fix: strategyList

- pom.xml
- [] 기능 추가
- [X ] 버그 수정
<br />
fix pom.xml duplicate
fix pom.xml duplicate
<br />
<br />
> fix pom.xml duplicate

- src/main/resources/application.properties
<br />
apllication.properties 속성 추가
<br />
apllication.properties 속성 추가
<br />
<br />
> apllication.properties 속성 추가

- src/main/java/com/sysmatic2/finalbe/attachment/controller/FileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/repository/FileMetadataRepository.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/S3ClientService.java
- src/test/java/com/sysmatic2/finalbe/attachment/controller/FileControllerTest.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/FileServiceTest.java
- [] 기능 추가
- [X ] 버그 수정
<br />
modify(File Attachment): modify download files
<br />
1. 파일 다운로드 에러 수정
<br />
- AmazonS3
<br />
> modify(File Attachment): modify download files

- src/main/java/com/sysmatic2/finalbe/member/controller/MemberController.java
- src/test/java/com/sysmatic2/finalbe/member/controller/AuthControllerTest.java
<br />
환경변수 주석 해제
<br />
환경변수 주석 해제
<br />
<br />
> 환경변수 주석 해제

- src/main/java/com/sysmatic2/finalbe/member/controller/MemberController.java
- src/test/java/com/sysmatic2/finalbe/member/controller/AuthControllerTest.java
<br />
Fix: 시큐리티 cofing 수정(cors허용)
<br />
1.시큐리티 config 수정(cors 허용설정)
2.CorConfig 추가
<br />
- jwt
- Security
<br />
> Fix: 시큐리티 cofing 수정(cors허용)

- src/main/resources/application.properties
<br />
SSL 설정 수정
<br />
SSL 설정 수정
<br />
<br />
> fix application.properties

- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsReqDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStrategicStatisticsEntity.java
- src/main/resources/application.properties
- [] 기능 추가
- [X ] 버그 수정
<br />
fix DailyStrategicStatisticsEntity relation
<br />
fix DailyStrategicStatisticsEntity mapsId 사용해 연관관계 매핑
<br />
<br />
> fix DailyStrategicStatisticsEntity relation

- src/main/resources/application.properties
- [] 기능 추가
- [] 리뷰 반영
<br />
application.properties SSL 주석 해제
<br />
application.properties SSL 주석 해제
<br />
<br />
> fix application.properties SSL

- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStrategicStatisticsHistoryEntity.java
- src/main/resources/application.properties
<br />
add DailyStrategicStatisticsEntity Realtion
<br />
add DailyStrategicStatisticsEntity Realtion
<br />
<br />
> add DailyStrategicStatisticsEntity Realtion

- src/main/resources/application.properties
- [] 기능 추가
<br />
add application.properties SSL
<br />
add application.properties SSL
<br />
<br />
> add application.properties SSL

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyAlreadyTerminatedException.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 운용종료 기능 추가
<br />
1. 전략 운용종료 기능 추가
2. 전략 운용종료 관련 커스텀 예외 추가
3. Global Exception Handler 수정
<br />
<br />
> [ADD] 전략 운용종료 기능 추가

- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsReqDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsHistoryRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
<br />
feature: add dailyStatisticsService
<br />
feature: add dailyStatisticsService
<br />
<br />
> feature: add dailyStatisticsService

- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
<br />
daily statistics service 타입 변경
<br />
daily statistics service int -> Integer
<br />
<br />
> [MODIFY] daily statistics service type

- src/main/java/com/sysmatic2/finalbe/exception/DailyDataNotEnoughException.java
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsHistoryRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 승인 요청 로직 변경
<br />
1. Strategy Service
전략 승인 요청시 매매일지 3개 미만일 경우 예외를 던지는 로직 추가
<br />
<br />
> [ADD] strategy approval request daily data validation

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyDataPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsReqDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsServiceTest.java
<br />
통계 등록 초기 구현
<br />
통계 등록 서비스, 컨트롤러, 서비스 목테스트
<br />
<br />
> feature: add statisticsService

- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsReqDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
- src/main/resources/application.properties
- [] 기능 추가
<br />
fix statisticsCalculate
<br />
fix statisticsCalculate
<br />
<br />
> fix statisticsCalculate

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
- src/main/resources/application.properties
- src/test/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsServiceTest.java
<br />
fix calculateStatistics
<br />
peak, peakRate 지표 추가
SM-SCORE, KP-RATIO 필드, 계산식 삭제 밑 전략 엔티티로 이동
<br />
<br />
> fix calculateStatistics

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyStatisticsResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
<br />
add DailyStatisticsList
<br />
통계 읽기. 일간분석 목록 읽어오기 구현.
<br />
<br />
> add DailyStatisticsList

- src/main/resources/application.properties
- [] 기능 추가
- [X ] 버그 수정
<br />
프로필 이미지 리팩토링 및 버그 해결
<br />
1. 프로필 파일 다운로드 이미지 변환 타입 버그 해결
2. 파일 업로드, 다운로드, 삭제 등 리팩토링
<br />
-AmazonS3
<br />
> modify(File Attachment): profile image

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProfileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/test/java/com/sysmatic2/finalbe/attachment/controller/ProfileControllerTest.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/FileServiceTest.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/ProfileServiceTest.java
- [] 기능 추가
<br />
프로필 이미지 리턴 타입 변경
<br />
1. 프로필 이미지 리턴 타입 url로 변경
2. 파일 서비스 기능 수정
<br />
AmazonS3
<br />
S3 정책 변경
> modify(File Attachment): profile image return type to url

- src/main/java/com/sysmatic2/finalbe/attachment/repository/FileMetadataRepository.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/IconService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/ProfileServiceTest.java
<br />
프로필 이미지 수정 및 아이콘 이미지 구현
<br />
1. 프로필 이미지 코드 리팩토링
2. 아이콘 이미지 서비스 초기 구현
<br />
AmazonS3
<br />
> feat(File Attachment): profile, icon

- src/main/java/com/sysmatic2/finalbe/exception/DuplicateDateException.java
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
<br />
fix followersCount issue
<br />
fix followersCount issue
<br />
<br />
> fix followersCount issue

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProposalController.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProposalService.java
<br />
제안서 파일 첨부 초기구현 및 아이콘 파일 첨부 서비스 수정
<br />
1. 제안서 파일 첨부 초기 구현
2. 아이콘 파일 첨부 서비스 코드 수정
<br />
AmazonS3
<br />
> feat(File Atachment) proposal service, controller and icon service

- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/util/StatisticsCalculator.java
<br />
일간 분석 수정 추가
<br />
일간 분석 수정 추가
<br />
<br />
> feature: add DailyStaitstics Update

- src/main/java/com/sysmatic2/finalbe/attachment/controller/IconController.java
- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProfileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProposalController.java
- src/main/java/com/sysmatic2/finalbe/attachment/repository/FileMetadataRepository.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/IconService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProposalService.java
<br />
아이콘 이미지 첨부 초기구현 및 제안서 첨부 수정
<br />
1. 아이콘 이미지 첨부 초기 구현
2. 제안서 첨부 수정
<br />
AmazonS3
<br />
> feat(File Attachment): Add icon, Modify proposal

- src/main/java/com/sysmatic2/finalbe/config/CorsConfig.java
- src/main/java/com/sysmatic2/finalbe/config/WebConfig.java
<br />
CORS 설정 수정
<br />
CORS 설정 수정
<br />
<br />
> CORS 설정 수정

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- [] 기능 추가
<br />
fix cors bug v3
<br />
fix cors bug v3
<br />
<br />
> fix cors bug v3

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- [] 기능 추가
<br />
fix cors bug v4
<br />
fix cors bug v4
<br />
<br />
> fix cors bug v4

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- [] 기능 추가
<br />
fix cors bug v5
<br />
fix cors bug v5
<br />
<br />
> fix cors bug v5

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/java/com/sysmatic2/finalbe/config/WebConfig.java
- [] 기능 추가
<br />
fix cors bug v6
<br />
fix cors bug v6
<br />
<br />
> fix cors bug v6

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/resources/application.properties
- [] 기능 추가
<br />
add application.properties session cookie setting
<br />
add application.properties session cookie setting
<br />
<br />
> add application.properties session cookie setting

- src/main/java/com/sysmatic2/finalbe/strategy/util/ExcelGenerator.java
<br />
ex) 
엑셀 제네레이터 추가
<br />
ex) 
엑셀 제네레이터 추가
<br />
ex)
<br />
> feat: 엑셀 만드는 유틸 클래스

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/DeleteDailyStatisticsRequestDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
<br />
feature: add DailyStatisticsDelete API
<br />
일간분석 등록 API 버그 수정. 일간분석 삭제 API 구현.
<br />
<br />
> feature: add DailyStatisticsDelete API

- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyProposalDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalService.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalServiceTest.java
- [] 기능 추가
<br />
add strategy proposalservice
<br />
1. add strategy proposalservice
<br />
AmazonS3
<br />
> feat(Strategy): add strategy proposalservice

- src/main/java/com/sysmatic2/finalbe/attachment/entity/FileMetadata.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyProposalRuntimeException.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyProposalEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyProposalRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
ex) 
bucket post 및 bucket list view 초기 구현
<br />
1. strategy proposal 중복 fileUrl 문제 해결
2.  프로필 이미지 로직 수정
3. 엔티티 nullable, unique 추가 설정
<br />
AmazonS3
<br />
> feat(Strategy, Profile): strategy proposal  및  프로필 이미지 로직 수정

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProposalController.java
- src/main/java/com/sysmatic2/finalbe/attachment/entity/FileMetadata.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyProposalRuntimeException.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyProposalEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyProposalRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
feat(Strategy): strategy proposal 수정
<br />
1. strategy proposal 중복 fileUrl 문제 해결
2. 제안서 테이블 엔티티 nullable, unique 추가 설정
<br />
AmazonS3
<br />
> feat(Strategy): strategy proposal 수정

- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/member/service/MemberHelper.java
- src/main/java/com/sysmatic2/finalbe/member/service/MemberService.java
<br />
feat(Profile): modify Profile logic
<br />
feat(Profile): modify Profile logic
<br />
AmazonS3
<br />
> feat(Profile): modify Profile logic

- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/member/service/MemberHelper.java
- [] 기능 추가
<br />
프로필 이미지를 회원 정보에 업데이트 수정
<br />
1. 프로필 이미지를 회원 정보에 업데이트 수정
<br />
AmazonS3
<br />
> feat(Profile) modify profile

- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- [] 기능 추가
<br />
제안서 등록 버그 수정
<br />
1. 제안서 등록 버그 수정
<br />
AmazonS3
<br />
> feat(Strategy): fix proposal 

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- [] 기능 추가
<br />
fix DailyStatistics Delete bug
<br />
fix DailyStatistics Delete bug
<br />
<br />
> fix DailyStatistics Delete bug

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProposalController.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- [] 기능 추가
<br />
fix(Strategy) : proposal bug
<br />
fix(Strategy) : proposal bug
<br />
AmazonS3
<br />
> fix(Strategy) : proposal bug

- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/resources/application.properties
<br />
StrategyResponseDTO 수정
<br />
<br />
<br />
> [MODIFY] StrategyResponseDTO 수정

- src/main/java/com/sysmatic2/finalbe/admin/controller/StrategyApprovalController.java
- src/main/java/com/sysmatic2/finalbe/admin/repository/StrategyApprovalRequestsRepository.java
- src/main/java/com/sysmatic2/finalbe/common/DtoEntityConversion.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 승인 요청 반려 로직 수정
<br />
<br />
<br />
> [Fix] Strategy Approval reject method

- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 상세페이지 제안서 파일명 반환 추가
<br />
1. StrategyService - 수정
2. StrategyResponseDto - 수정
<br />
<br />
> [MODIFY] Strategy Detail - Proposal File Title

- src/main/java/com/sysmatic2/finalbe/strategy/controller/ExcelUploadController.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/ExcelUploadService.java
- src/test/java/com/sysmatic2/finalbe/strategy/controller/ExcelUploadControllerTest.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/ExcelUploadServiceTest.java
<br />
엑셀 업로드 API 엔드포인트 구현
<br />
ExcelUploadController를 생성하여 /api/strategies/{strategyId}/upload 엔드포인트 추가.
MultipartFile을 통해 엑셀 파일 업로드 기능 구현.
<br />
ex)
<br />
> feat: 엑셀 업로드 API 구현 및 Swagger 문서화

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProfileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProposalService.java
- src/main/java/com/sysmatic2/finalbe/exception/InvalidFileNameException.java
- src/main/java/com/sysmatic2/finalbe/exception/LiveAccountDataException.java
- src/main/java/com/sysmatic2/finalbe/exception/S3FileUploadFailedException.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/util/FileValidator.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/FileServiceTest.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/S3ClientServiceTest.java
<br />
feat(Profile): modify profile getting url
feat(Profile): modify profile getting url
<br />
AmazonS3
<br />
> feat(Profile): modify profile getting url

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProfileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/IconService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProposalService.java
- src/main/java/com/sysmatic2/finalbe/exception/FileMetadataDeleteFailedException.java
- src/main/java/com/sysmatic2/finalbe/exception/FileMetadataNotFoundException.java
- src/main/java/com/sysmatic2/finalbe/exception/InvalidCategoryException.java
- src/main/java/com/sysmatic2/finalbe/exception/InvalidFileNameException.java
- src/main/java/com/sysmatic2/finalbe/exception/LiveAccountDataException.java
- src/main/java/com/sysmatic2/finalbe/exception/MetadataNotFoundException.java
- src/main/java/com/sysmatic2/finalbe/exception/S3FileDeleteFiledException.java
- src/main/java/com/sysmatic2/finalbe/exception/S3FileUploadFiledException.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyProposalNotFoundException.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyProposalSaveException.java
- src/main/java/com/sysmatic2/finalbe/exception/UnauthorizedAccessException.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyProposalService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/java/com/sysmatic2/finalbe/util/FileValidator.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/FileServiceTest.java
- src/test/java/com/sysmatic2/finalbe/attachment/service/S3ClientServiceTest.java
- [] 기능 추가
<br />
feat(File Attachment): fix upload method
<br />
1. File 업로드 파라미터 추가
2. profile, icon, proposal file 업로드 파라미터 수정
3. 커스텀 예외 추가
<br />
AmazonS3
<br />
> feat(File Attachment): fix upload method

- src/main/java/com/sysmatic2/finalbe/common/DtoEntityConversion.java
- src/main/java/com/sysmatic2/finalbe/member/service/MemberService.java
- src/main/java/com/sysmatic2/finalbe/strategy/common/DailyStatisticsCalculator.java
- src/main/java/com/sysmatic2/finalbe/strategy/common/MonthlyStatisticsCalculator.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/MonthlyAnalysisResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/MonthlyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/MonthlyStatisticsHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/MonthlyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/DailyStatisticsService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/MonthlyStatisticsService.java
- src/test/java/com/sysmatic2/finalbe/strategy/service/ExcelGeneratorServiceTest.java
<br />
feature: add MonthlyStatistics
<br />
1. 월간분석 업데이트
2. 월간분석 목록 API
<br />
<br />
> feature: add MonthlyStatistics

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/AdvancedSearchResultDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
목록들 차트 누적 데이터 반환값 포함
<br />
1. 랭킹 리스트
2. 상세 검색 필터링 리스트
3. 나의 전략 리스트(트레이더)
4. 통합검색 리스트
<br />
<br />
> feature: add chart data

- src/main/java/com/sysmatic2/finalbe/attachment/controller/ProfileController.java
- src/main/java/com/sysmatic2/finalbe/attachment/repository/FileMetadataRepository.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/exception/LiveAccountDataNotFoundException.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/LiveAccountDataController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/LiveAccountDataDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/LiveAccountDataPageResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/LiveAccountDataResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/LiveAccountDataEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/LiveAccountDataHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/LiveAccountDataRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/LiveAccountDataService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
feat(File attachment): Add liveAccountData, modify profile
1. 실계좌 인증 기능 추가(등록, 삭제, 조회)
2. 등록된 프로필 없을 시, null 값 반환 
<br />
AmazonS3
<br />
> feat(File attachment): Add liveAccountData, modify profile

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
<br />
전략 등록, 수정, 삭제 접속자 정보 등록
<br />
1. StrategyController - 수정
<br />
<br />
> [Add] 전략 등록, 수정, 삭제 접속자 정보 등록

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
> [SYNC] MAIN-DEV 12/2 16:22

- src/main/java/com/sysmatic2/finalbe/member/repository/MemberRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
<br />
메인페이지용 승인된전략, 트레이더 수 반환 메서드 추가
<br />
1. Strategy Repository - 수정
2. Member Repository - 수정
3. Strategy Controller - 수정
<br />
<br />
> [ADD] Strategy Trader Counter

- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/exception/InvalidFieldNameException.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/DailyStatisticsChartResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/DailyStatisticsHistoryEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustom.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
feature: add strategyChartDetail
<br />
feature: add strategyChartDetail
<br />
<br />
> feature: add strategyChartDetail

- src/main/java/com/sysmatic2/finalbe/config/SwaggerConfig.java
- src/main/java/com/sysmatic2/finalbe/controller/SwaggerController.java
<br />
스웨거 토큰 설정
<br />
스웨거 토큰 설정
<br />
<br />
> feature: add swaggerConfig

- src/main/java/com/sysmatic2/finalbe/attachment/service/FileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/IconService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProfileService.java
- src/main/java/com/sysmatic2/finalbe/attachment/service/ProposalService.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/LiveAccountDataController.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/LiveAccountDataService.java
- [] 기능 추가
<br />
feat(File Attachment): 파일 업로드시, displayName 인자 삭제
<br />
feat(File Attachment): 파일 업로드시, displayName 인자 삭제
<br />
AmazonS3
<br />
> feat(File Attachment): 파일 업로드시, displayName 인자 삭제

- src/main/java/com/sysmatic2/finalbe/member/controller/MemberController.java
<br />
feat: add swaggerLogin
<br />
feat: add swaggerLogin
<br />
<br />
> feat: add swaggerLogin

- src/main/java/com/sysmatic2/finalbe/strategy/controller/LiveAccountDataController.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/LiveAccountDataRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/LiveAccountDataService.java
<br />
feat: 로그인 코드 추가 및 실계좌 인증 다중 리스트 삭제 추가
<br />
1. 로그인 코드 추가
2. 실계좌 인증 다중 리스트 삭제 추가
<br />
AmazonS3
jwt
<br />
> feat: 로그인 코드 추가 및 실계좌 인증 다중 리스트 삭제 추가

- src/main/java/com/sysmatic2/finalbe/exception/ReviewNotFoundException.java
- src/main/java/com/sysmatic2/finalbe/exception/StrategyReviewFailedException.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyReviewController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyReviewDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyReviewPageResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyReviewEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyReviewRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyReviewService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 리뷰 기능 추가
<br />
1. review 기능 CRUD 구현 완료
<br />
<br />
> feat(Strategy Review): review 기능 추가

- src/main/java/com/sysmatic2/finalbe/member/controller/TraderStrategyController.java
- src/main/java/com/sysmatic2/finalbe/member/dto/SimpleProfileDTO.java
- src/main/java/com/sysmatic2/finalbe/member/dto/TraderSearchResultDto.java
- src/main/java/com/sysmatic2/finalbe/member/repository/MemberRepository.java
- src/main/java/com/sysmatic2/finalbe/member/repository/MemberRepositoryCustom.java
- src/main/java/com/sysmatic2/finalbe/member/repository/MemberRepositoryCustomImpl.java
- src/main/java/com/sysmatic2/finalbe/member/service/MemberService.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
- src/test/java/com/sysmatic2/finalbe/member/controller/MemberControllerTest.java
<br />
feature: add searchTraderList
<br />
feature: add searchTraderList
<br />
<br />
> feature: add searchTraderList

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
add updateFollowersCount
<br />
add updateFollowersCount
<br />
<br />
> add updateFollowersCount

- src/main/java/com/sysmatic2/finalbe/common/EmailTemplate.java
- src/main/java/com/sysmatic2/finalbe/member/controller/AuthController.java
- src/main/java/com/sysmatic2/finalbe/member/controller/MemberController.java
- src/main/java/com/sysmatic2/finalbe/member/service/EmailService.java
- src/test/java/com/sysmatic2/finalbe/member/service/EmailServiceTest.java
<br />
이메일 템플릿 추가
<br />
이메일 템플릿 추가
<br />
<br />
> Add email template

- src/main/java/com/sysmatic2/finalbe/admin/repository/StrategyApprovalRequestsRepository.java
- src/main/java/com/sysmatic2/finalbe/admin/service/StrategyApprovalRequestsService.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
<br />
전략승인요청목록, 전략 랭킹목록 로직 수정
<br />
1. 전략승인요청목록 - 승인, 승인요청대기 중인 요청목록만 반환
2. 전략랭킹 - 승인받은 전략만 반환
<br />
<br />
> [MODIFY] 전략승인요청목록, 전략목록승인여부

- src/main/java/com/sysmatic2/finalbe/cs/service/ConsultationService.java
<br />
상담 목록 조회 시 정렬 기준(createdAt 내림차순)을 일관성 있게 유지하기 위한 공통 PageRequest 적용 
<br />
PageRequest에 정렬 기준(createdAt 내림차순)을 설정하여 필터링된 결과에서도 최신순 조회를 보장
<br />
ex)
<br />
> 문의 api 정렬 수정

- src/main/java/com/sysmatic2/finalbe/member/service/FollowingStrategyService.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/AdvancedSearchResultDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/SmScoreRankingResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
top 5 sm score 전략 리스트 구현
<br />
top 5 sm score 전략 리스트 구현
<br />
<br />
> feature: add top5-sm-score

- src/main/java/com/sysmatic2/finalbe/admin/controller/InvestmentAssetClassesController.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/InvestmentAssetClassesDto.java
- src/main/java/com/sysmatic2/finalbe/admin/dto/InvestmentAssetClassesPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/admin/entity/InvestmentAssetClassesEntity.java
- src/main/java/com/sysmatic2/finalbe/admin/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/common/DtoEntityConversion.java
- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
<br />
1. Spring Security Config 전략, 관리자 파트 추가
2. 투자자산 분류 입력 반환값 수정 
<br />
1. Spring Security Config 전략, 관리자 파트 추가
2. 투자자산 분류 입력 반환값 수정
<br />
<br />
> [ADD] 전략, 관리자 관련 Spring Security Config 설정, 투자자산 분류 코드 수정

- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- [] 기능 추가
<br />
fix top5-sm-score isApproved&isPosted
<br />
fix top5-sm-score isApproved&isPosted
<br />
<br />
> fix top5-sm-score isApproved&isPosted

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/java/com/sysmatic2/finalbe/member/controller/TraderStrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/LiveAccountDataController.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/LiveAccountDataService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/resources/application.properties
<br />
실계좌 인증 권한 설정, 나의 전략 권한 세부 설정
<br />
1. 실계좌 인증 권한 설정
실계좌 인증와 관련된 메서드에 권한 설정 구현
2. 나의 전략 권한 세부 설정
나의 전략 - 권한 별 전략 목록 반환 메서드 구현
<br />
<br />
> [ADD] 실계좌 인증 권한 설정, 나의 전략 권한 세부 설정

- src/main/java/com/sysmatic2/finalbe/admin/service/TradingTypeService.java
- src/main/java/com/sysmatic2/finalbe/strategy/entity/StrategyEntity.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/DailyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/MonthlyStatisticsRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- [] 기능 추가
<br />
매매유형 삭제 & 전략 삭제 수정
<br />
전략 삭제에 일간분석/월간분석 삭제 추가
매매유형 삭제 FK 제약조건 버그 수정
<br />
<br />
> fix tradingType-delete & strategy-delete

- src/main/java/com/sysmatic2/finalbe/admin/controller/InvestmentAssetClassesController.java
- src/main/java/com/sysmatic2/finalbe/admin/controller/TradingTypeController.java
- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/java/com/sysmatic2/finalbe/exception/DeleteTradingTypeStrategyExistException.java
- src/main/java/com/sysmatic2/finalbe/exception/GlobalExceptionHandler.java
- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
<br />
투자자산 분류 다중삭제 구현
<br />
1. 투자자산 분류 다중삭제 구현
2. 매매유형 다중 삭제 구현
3. 관련 예외 handler 구현
<br />
<br />
> [MODIFY] 투자자산 분류 다중삭제 구현

- src/main/java/com/sysmatic2/finalbe/strategy/controller/StrategyController.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/SearchOptionsDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/SearchOptionsPayloadDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyRepositoryCustomImpl.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 상세 필터링에 키워드 검색 추가
<br />
1. StrategyRepositoryCustomImpl - 수정
2. StrategyService - 수정
3. StrategyController - 수정
4. SearchOptionsDto - 수정
5. SearchOptionsPayloadDto - 수정
<br />
<br />
> [MODIFY] Add keyword search for Advanced Search

- src/main/java/com/sysmatic2/finalbe/admin/repository/InvestmentAssetClassesRepository.java
- src/main/java/com/sysmatic2/finalbe/admin/service/InvestmentAssetClassesService.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
투자자산 분류 목록 못가져오던 것 수정
<br />
1. IAC repository - 수정
2. StrategyService - 수정
<br />
<br />
> [FIX] IAC repository method

- src/main/java/com/sysmatic2/finalbe/strategy/repository/StrategyReviewRepository.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyReviewService.java
- [] 기능 추가
<br />
fix reviewDelete bug
<br />
fix reviewDelete bug
<br />
<br />
> fix reviewDelete bug

- src/main/java/com/sysmatic2/finalbe/config/SecurityConfig.java
- src/main/java/com/sysmatic2/finalbe/strategy/dto/StrategyResponseDto.java
- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
- src/main/resources/application.properties
<br />
전략 승인요청 가능 여부 플래그 추가
<br />
1. StrategyResponseDTO - 수정
2. StrategyService - 수정
<br />
<br />
> [ADD] Strategy request available flag in responseDTO

- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 승인요청 가능 여부 플래그 로직 변경
<br />
1. StrategyService - 수정
<br />
<br />
백프 배포 nginx 검토
> [MODIFY] Strategy Detail requestAvailable flag logic

- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
<br />
전략 삭제 로직 변경
<br />
전략 삭제시 전략승인요청 내역도 삭제
<br />
<br />
> [FIX] Strategy Delete Logic

- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
> [SYNC] MAIN - DEV 13:43

- src/main/java/com/sysmatic2/finalbe/strategy/service/StrategyService.java
> [SYNC] MAIN - DEV 12/6 14:04
